src/Entity/StTrick.php
<?php

namespace App\Entity;

use App\Repository\StTrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=StTrickRepository::class)
 * @UniqueEntity(
 *     fields = {"nom"},
 *     message = "Ce nom est déjà utilisé"
 * )
 */
class StTrick
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\OneToMany(targetEntity=StIllustration::class, mappedBy="trick", orphanRemoval=true)
     */
    private $illustrations;

    /**
     * @ORM\OneToMany(targetEntity=StVideo::class, mappedBy="trick", orphanRemoval=true)
     */
    private $videos;

    /**
     * @ORM\OneToMany(targetEntity=StCommentaire::class, mappedBy="trick", orphanRemoval=true)
     */
    private $commentaires;

    /**
     * @ORM\ManyToOne(targetEntity=StUtilisateur::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity=StGroupe::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $groupe;

    /**
     * @ORM\OneToOne(targetEntity=StIllustration::class, cascade={"persist", "remove"})
     */
    private $favorite_illustration;

    public function __construct()
    {
        $this->date = new \DateTime();
        $this->illustrations = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->nom);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getIllustrations(): Collection
    {
        return $this->illustrations;
    }

    public function addIllustration(StIllustration $illustration): self
    {
        if (!$this->illustrations->contains($illustration)) {
            $this->illustrations[] = $illustration;
            $illustration->setIdTrick($this);
        }

        return $this;
    }

    public function removeIllustration(StIllustration $illustration): self
    {
        if ($this->illustrations->removeElement($illustration)) {
            // set the owning side to null (unless already changed)
            if ($illustration->getIdTrick() === $this) {
                $illustration->setIdTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|StVideo[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(StVideo $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setIdTrick($this);
        }

        return $this;
    }

    public function removeVideo(StVideo $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getIdTrick() === $this) {
                $video->setIdTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|StCommentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(StCommentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setIdTrick($this);
        }

        return $this;
    }

    public function removeCommentaire(StCommentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getIdTrick() === $this) {
                $commentaire->setIdTrick(null);
            }
        }

        return $this;
    }

    public function getUtilisateur(): ?StUtilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?StUtilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getGroupe(): ?StGroupe
    {
        return $this->groupe;
    }

    public function setGroupe(?StGroupe $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }

    public function getFavoriteIllustration(): ?StIllustration
    {
        return $this->favorite_illustration;
    }

    public function setFavoriteIllustration(?StIllustration $favorite_illustration): self
    {
        $this->favorite_illustration = $favorite_illustration;

        return $this;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\StTrick;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('groupe')
            ->add('create', SubmitType::class, ['label' => 'Créer le trick'])
            ->add('createThenMedia', SubmitType::class, ['label' => 'Ajouter des médias'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => StTrick::class,
        ]);
    }
}

src/Controller/TricksController.php
<?php

namespace App\Controller;

use App\Entity\StCommentaire;
use App\Entity\StIllustration;
use App\Entity\StTrick;
use App\Form\CommentaireType;
use App\Form\EditTrickType;
use App\Form\TrickType;
use App\Repository\StCommentaireRepository;
use App\Repository\StIllustrationRepository;
use App\Repository\StTrickRepository;
use App\Repository\StUtilisateurRepository;
use App\Service\FileUploader;
use Doctrine\ORM\NonUniqueResultException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TricksController extends AbstractController
{
    /**
     * @Route("/tricks/{slug}-{id}", name="tricks.show", requirements={"slug": "[a-z0-9\-]+"})
     * @param StTrick $trick
     * @param string $slug
     * @param StUtilisateurRepository $userRepo
     * @param Request $request
     * @return Response
     */
    public function show(StTrick $trick, string $slug, StUtilisateurRepository $userRepo, Request $request): Response
    {
        if ($trick->getSlug() !== $slug) {
            return $this->redirectToRoute('tricks.show', [
                'id' => $trick->getId(),
                'slug' => $trick->getSlug()
            ], 301);
        }

        $commentaire = new StCommentaire();

        $form = $this->createForm(CommentaireType::class, $commentaire);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $manager = $this->getDoctrine()->getManager();
            $commentaire->setTrick($trick);
            $commentaire->setUtilisateur($userRepo->loadActualUser($this->getUser()));

            $manager->persist($commentaire);
            $manager->flush();

            return $this->redirectToRoute("tricks.show", [
                'id' => $trick->getId(),
                'slug' => $trick->getSlug()
            ]);
        }

        return $this->render("tricks/show.html.twig", [
            'trick' => $trick,
            'commentForm' => $form->createView()
        ]);
    }

    /**
     * @param Request $request
     * @param StUtilisateurRepository $userRepo
     * @return Response
     *
     * @throws NonUniqueResultException
     * @Route("/tricks/creation", name="tricks.create")
     */
    public function create(Request $request, StUtilisateurRepository $userRepo): Response
    {
        $trick = new StTrick();

        $form = $this->createForm(TrickType::class, $trick);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $manager = $this->getDoctrine()->getManager();

            $trick->setUtilisateur($userRepo->loadActualUser($this->getUser()));
            $manager->persist($trick);

            $manager->flush();

            if($form->get('createThenMedia')->isClicked()) {
                return $this->redirectToRoute("tricks.addMedia", [
                    'id' => $trick->getId(),
                    'slug' => $trick->getSlug()
                ]);
            }

            return $this->redirectToRoute("home");
        }

        return $this->render('tricks/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/tricks/delete/{id}", name="tricks.delete")
     * @param StTrick $trick
     * @return Response
     */
    public function delete(StTrick $trick): Response
    {
        $this->denyAccessUnlessGranted('ROLE_EDITOR');

        $manager = $this->getDoctrine()->getManager();
        $manager->remove($trick);
        $manager->flush();

        return $this->redirectToRoute("home");
    }

    /**
     * @Route("/tricks/addMedia/{slug}-{id}", name="tricks.addMedia", requirements={"slug": "[a-z0-9\-]+"})
     * @param Request $request
     * @param StTrick $trick
     * @param string $slug
     * @param FileUploader $fileUploader
     * @return RedirectResponse|Response
     */
    public function addMedia(Request $request, StTrick $trick, string $slug, FileUploader $fileUploader): RedirectResponse|Response
    {
        if ($trick->getSlug() !== $slug) {
            return $this->redirectToRoute('tricks.addMedia', [
                'id' => $trick->getId(),
                'slug' => $trick->getSlug()
            ], 301);
        }

        if ($request->getMethod() == "POST") {
            $manager = $this->getDoctrine()->getManager();

            $file = new UploadedFile($_FILES['file']['tmp_name'], $_FILES['file']['name']);

            $illustrationFileName = $fileUploader->upload($file, 'images');

            $illustration = new StIllustration();
            $illustration->setTrick($trick);
            $illustration->setUrl($illustrationFileName);

            $manager->persist($illustration);
            $manager->flush();
        }

        return $this->render("tricks/addMedia.html.twig", [
            'trick' => $trick
        ]);
    }

    /**
     * @Route("/tricks/setFavorite/{id}", name="tricks.setFavorite")
     * @param Request $request
     * @param StTrick $trick
     * @param StIllustrationRepository $illustration_rep
     * @return Response
     */
    public function setFavorites(Request $request, StTrick $trick, StIllustrationRepository $illustration_rep): Response
    {
        $this->denyAccessUnlessGranted('ROLE_EDITOR');
        $illustration_id = $request->request->get('illustration-id');
        $illustration = $illustration_rep->find($illustration_id);

        $manager = $this->getDoctrine()->getManager();
        $trick->setFavoriteIllustration($illustration);
        $manager->persist($trick);
        $manager->flush();

        return new Response('200');
    }

    /**
     * @Route("/tricks/modification/{slug}-{id}", name="tricks.modify", requirements={"slug": "[a-z0-9\-]+"})
     * @param Request $request
     * @param StTrick $trick
     * @param string $slug
     * @return RedirectResponse|Response
     */
    public function modify(Request $request, StTrick $trick, string $slug): RedirectResponse|Response
    {
        if ($trick->getSlug() !== $slug) {
            return $this->redirectToRoute('tricks.addMedia', [
                'id' => $trick->getId(),
                'slug' => $trick->getSlug()
            ], 301);
        }

        $form = $this->createForm(EditTrickType::class, $trick);

        $form->handleRequest($request);

        if ($request->getMethod() == "POST") {
            $manager = $this->getDoctrine()->getManager();

            $manager->persist($trick);
            $manager->flush();

            return $this->redirectToRoute('tricks.show', [
                'id' => $trick->getId(),
                'slug' => $trick->getSlug()
            ], 301);
        }

        return $this->render("tricks/create.html.twig", [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/tricks/deleteIllustration", name="tricks.deleteIllustration",)
     */
    public function deleteIllustration(Request $request, StIllustrationRepository $illustrationRep, StTrickRepository $trickRepo)
    {
        $this->denyAccessUnlessGranted('ROLE_EDITOR');

        $illustrationId = $request->request->get('illustrationId');
        $illustration = $illustrationRep->find($illustrationId);

        $manager = $this->getDoctrine()->getManager();

        if($request->request->get('favorite')) {
            $trick = $trickRepo->find($illustration->getTrick());
            $trick->setFavoriteIllustration(null);
            $manager->persist($trick);
        }

        $manager->remove($illustration);
        $manager->flush();

        return new Response('200');
    }
}

templates/tricks/addMedia.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tricks - Media' %}

{% block stylesheets %}
    <link href="{{ asset('css/addMedia.tricks.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Ajouter des medias</h1>
        <div class="row">
            <form method="POST" enctype="multipart/form-data">
                <div class="form-field">
                    <label for="file">Ajouter des photos:</label>
                    <input type="file" id="file" name="file" class="form-control">
                </div>
                <div class="container mt-2 illustrationsContainer d-flex flex-wrap">
                    {% for illustration in trick.illustrations %}
                        <div class="p-2 illustrationContainer" data-id_illustration="{{ illustration.id }}">
                            <img class="mr-3 mb-3 border border-white rounded" src="{{ asset('/media/images/' ~ illustration.url)|imagine_filter('squared_thumbnail_small') }}" alt="Illustration">
                            <div class="illustrationActions"  data-illustration_id="{{ illustration.id }}">
                                <button type="button" class="illustrationFavButton btn btn-warning">
                                    <span
                                            class="{% if trick.favoriteIllustration == illustration %}fas{% else %}far{% endif %} fa-star"
                                    ></span>
                                </button>
                                <button type="button" class="illustrationDeleteButton btn btn-danger"><span class="fas fa-times"></span></button>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </form>
            <a href="{{ path('tricks.show', {id: trick.id, slug: trick.slug}) }}"><button class="btn btn-primary">Valider</button></a>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
            $('.illustrationFavButton').on('click', (e) => {
                let illustrationId = $(e.target).parents('.illustrationContainer').data('id_illustration');

                $.ajax({
                    url: '{{ path('tricks.setFavorite', {id: trick.id}) }}',
                    type: "POST",
                    dataType: "json",
                    data: {
                        "illustration-id": illustrationId
                    },
                    async: true,
                    success: function () {
                        $('.fas.fa-star').removeClass('fas')
                            .addClass('far');

                        $('.illustrationContainer[data-id_illustration='+illustrationId+'] button.illustrationFavButton span').removeClass('far')
                            .addClass('fas');
                    }
                });
            });

            $('.illustrationDeleteButton').on('click', (e) => {
                let illustrationContainer = $(e.target).parents('.illustrationContainer');
                let illustrationId = illustrationContainer.data('id_illustration');

                let data = {
                    "illustrationId": illustrationId,
                    "favorite" : $('.illustrationFavButton span', illustrationContainer).hasClass('fas')
                };

                $.ajax({
                    url: '{{ path('tricks.deleteIllustration') }}',
                    type: "POST",
                    dataType: "json",
                    data: data,
                    async: true,
                    success: function () {
                        illustrationContainer.remove();
                    }
                });
            });
    </script>
    <script src="{{ asset('js/addMedia.trick.js') }}" crossorigin="anonymous"></script>
{% endblock %}

templates/tricks/create.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tricks - Nouveau' %}

{% block body %}
    {{ form_start(form) }}
        {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/tricks/show.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tricks' %}

{% block stylesheets %}
    <link href="{{ asset('css/show.tricks.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="container">
            <img
                    {% if trick.illustrations is empty %}
                        src="{{ asset('/media/images/default.jpg') }}"
                    {% else %}
                        {% if trick.favoriteIllustration is empty %}
                            src="{{ asset('/media/images/' ~ trick.illustrations|first.url) }}"
                        {% else %}
                            src="{{ asset('/media/images/' ~ trick.favoriteIllustration.url) }}"
                        {% endif %}
                    {% endif %}
                    alt="Snow"
                    class="img-fluid"
            >
            {% if is_granted('ROLE_EDITOR') %}
                <div id="tricksAction">
                    <a id="trickAddMediaButton" href="{{ path('tricks.addMedia', {id: trick.id, slug: trick.slug}) }}"><button class="btn btn-primary"><span class="fas fa-camera"></span></button></a>
                    <a id="trickModifyButton" href="{{ path('tricks.modify', {id: trick.id, slug: trick.slug}) }}"><button class="btn btn-primary"><span class="fas fa-pen"></span></button></a>
                    <a id="trickDeleteButton" href="{{ path('tricks.delete', {id: trick.id}) }}"><button class="btn btn-danger"><span class="fas fa-times"></span></button></a>
                </div>
            {% endif %}
        </div>
        <div class="centered"><h1>{{ trick.nom }}</h1></div>
    </div>
    <div class="container mt-2">
        {% for illustration in trick.illustrations %}
            {% if illustration != trick.favoriteIllustration %}
                <img class="mr-3 mb-3 border border-white rounded" src="{{ asset('/media/images/' ~ illustration.url)|imagine_filter('squared_thumbnail_small') }}" alt="Illustration">
            {% endif %}
        {% endfor %}
        <div class="embed-responsive embed-responsive-16by9">
            {% for video in trick.videos %}
                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ video.url }}?rel=0" allowfullscreen></iframe>
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <p>{{ trick.description }}</p>
    </div>
    {% if app.user %}
        <div class="container">
            {{ form_start(commentForm) }}
                {{ form_widget(commentForm) }}
                <button type="submit" class="btn btn-primary">Valider</button>
            {{ form_end(commentForm) }}
        </div>
    {% endif %}
    <div class="container">
        {% for commentaire in trick.commentaires %}
            <span class="fas fa-pencil"></span> {{ commentaire.utilisateur.nom }} {{ commentaire.utilisateur.prenom }} le {{ commentaire.date | date("d/m/Y à H:i") }}
            <p>
                {{ commentaire.contenu }}
            </p>
        {% endfor %}
    </div>
{% endblock %}